### ISSUE TITLE
Indexer Stalled with Error: OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed on transportation layer, not open, Connection refused (os error 111)

### ISSUE THREAD

**Issue by spidey-169** [Zondax/namadexer#146]
My Indexer is currently stalled at block 36103 "http://namada-indexer.spidey.services/block/last". I am getting the following error in my indexer logs. I am using the latest tag [v0.1.0-rc.5](https://github.com/Zondax/namadexer/releases/tag/v0.1.0-rc.5) and I have confirmed that my RPC endpoint for my indexer is running correctly and at the latest block. (http://namada-rpc.spidey.services)

```
OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed on transportation layer, not open, Connection refused (os error 111)
```

My docker containers have been up for last 23 hours
```
7cc9901d853d   namadexer-server    "/bin/bash -c /usr/l…"   23 hours ago   Up 23 hours             server
dc26c850604b   namadexer-indexer   "/bin/bash -c ' /usr…"   23 hours ago   Up 23 hours             indexer
c571055a1f92   postgres:14         "docker-entrypoint.s…"   23 hours ago   Up 23 hours             postgres
```

@rllola Tagging you here. Thanks

**Comment by rllola** [comment]
I am actually not that familiar with openTelemetry. @neithanmo do you know what could trigger this ?

**Comment by spidey-169** [comment]
> I am actually not that familiar with openTelemetry. @neithanmo do you know what could trigger this ?

Thanks, I have gotten this in the older version and I know a few folks who have faced this in the newer version too. Hence might be worth exploring or having a little more clarity on this!

**Comment by neithanmo** [comment]
@spidey-169 
The error message you've shared with Jaeger seems to indicate a connectivity issue between the Jaeger service integrated within the indexer and the Jaeger collector service. This problem typically arises when the indexer attempts to transmit telemetry data, including traces and metrics, but finds the Jaeger collector either inaccessible or not running.

please ensure either:

- If you prefer to handle telemetry data locally, ensure that the Jaeger collector is up and running on your machine before initiating the indexer. 
- Alternatively, if your telemetry data management strategy involves a remote setup, you can specify the address of an external Jaeger collector within the indexer's configuration file.

Regardless of the chosen method, it's essential to ensure that the Jaeger collector's status is active and ready to accept connections before the indexer is launched. 

Otherwise, you can also disable Jaeger telemetry in the configuration file.

**Comment by neithanmo** [comment]
@spidey-169 does this problem persist in your setup? even after trying what I mentioned in my previous response?

**Comment by rllola** [comment]
Hey @spidey-169 any updates on this ?

**Comment by spidey-169** [comment]
> Hey @spidey-169 any updates on this ? 

Looks like this issues is not there anymore for me. However, I do need to restart indexer as it stalls in between

**Comment by rllola** [comment]
Yes, you should but the latest release (https://github.com/Zondax/namadexer/releases/tag/v1.0.0) should fix this issue. We found the problem was related to a dependency and they kindly merged a fix.

Closing this issue as it the error is no showing anymore.
