### ISSUE TITLE
Parallelize insertion of txs

### ISSUE THREAD

**Issue by gnosed** [Zondax/namadexer#42]
The insertion of txs `tx_transfer` is currently done sequentially. This make the indexer slower than the actual progress of the Namada chain, mainly when blocks start containing about more than 250 txs.

In the indexer I am currently using for the Namada Explorer, I use `tokio` to parallelize the insertion of txs, this works quite well.

**Comment by rllola** [comment]
Indeed it slows down things. I would rather avoid using `tokio` to parallelize and use batch insert instead.

**Comment by neithanmo** [comment]
We are indeed doing batch inserts for transactions. it should be possible to spawn a new job that does batching inserts, but this could just move the bottleneck to the database contention system because there would be more than one task at the time performing queries to the database, not only readings.

How much performance/speed-up did you get? after doing this?

our current benchmark is limited to 300 blocks without that amount of transactions per block. if you can provide a good benchmark(that would be nice),  we might consider the concurrent option using Tokio or evaluate other options.

**Comment by neithanmo** [comment]
after looking at this we decided that we can do batch insertions of transactions(the common parts) but we can not parallelize, the reason is simple, **data integrity**.
We are currently using the postgres-transaction mechanism, to ensure that a block is stored in the database only if each of its parts is so.  we can do contention with a mutex but it would likely slow down the process overall(assumption, further investigation, and benchmarking need to be done).
